sudo: true
dist: trusty

language: go

os:
  - linux

git:
  depth: 3

before_script:
  - go version
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - make build
  - go test -v -covermode=atomic -coverprofile=coverage.out ./...
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload';
