version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4557-4599:4557-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=lambda,apigateway,s3,cloudformation,iam,sts,ses,dynamodb
      - DEBUG=1
        #- DATA_DIR=/tmp/localstack/data
      - HOSTNAME=localhost
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
        #- "localstack-vol:/tmp/localstack" #use a volume not a path
      - "/var/run/docker.sock:/var/run/docker.sock"
