service: listing-db
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws

resources:
  Resources:
    SubscriptionsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: newsletter
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: newsletter
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
         # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
  Outputs:
    SubscriptionsTableArn:
      Description: The ARN of the subscription table
      Value:
        Fn::GetAtt:
          - SubscriptionsDynamoDBTable
          - Arn
      Export:
        Name: ${self:provider.stage}-SubscriptionsTableArn

custom:
  tableName: ${opt:stage, 'dev'}-subscribers

